### ISSUE TITLE
Mi Band 4: can't change location for weather

### ISSUE THREAD

**Issue by JPFrancoia** [Freeyourgadget/Gadgetbridge#1609]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
I bought, paired and initialized my watch ~3 days ago, when I was in Cambridge (UK). My location was picked up and the weather info displayed (on the watch) in the "weather" menu is for Cambridge.

But I was there only for a couple of days. I live in the Netherlands. I can't change the location for the weather menu. In the settings, there is a menu called "weather", but it only contains "weather location (CM/LOS)". I don't use CM or LOS. I tried the procedure mentioned here: https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather, which had no effect.

How do I change the location for the weather menu please?

EDIT: after investigation and input from several people, we realised that the weather info (temperature, air index and forecast) is indeed refreshed by weather notifications (see wiki link above). What **isn't** updated is the location name in the weather menu on the band. See comments below for an image. The current situation is: temperature displayed is for location set in the weather notifications app (on the phone). Location name displayed is the location when band was first paired. Eg: temperature of 30°C (Paris), while location name is "Cambridge".

#### Your wearable device is:

Mi band 4

#### Your android version is:

Custom ROM

#### Your Gadgetbridge version is:

0.35.2

**Comment by desperadoduck** [comment]
Probably your weather info isn't getting updated at all. I had the same problem. I solved it by installing the app "weather notification" which can be found here: https://bitbucket.org/gelin/weather-notification
Perhaps this should be documented somewhere in the wiki if it isn't. I got the hint by reading the source ;-)

**Comment by desperadoduck** [comment]
Ah your link shows that it is documented. I've no idea why it doesn't work for you though, I did pretty much the same.

**Comment by JPFrancoia** [comment]
Did you get a new item in the "weather" menu, in general settings?

**Comment by desperadoduck** [comment]
No, nothing in gadgetbridge changed. But I've hit the reload button on the gadgetbridge main screen. Did you try that?

**Comment by JPFrancoia** [comment]
The one where you can see the device's status? Where you can disconnect the device? Yes I hit the reload button, many many times. I also rebooted the watched several times.

**Comment by desperadoduck** [comment]
Yes, that one. :-/ I'm not sure if it matters here, but did you give gadgetbridge notification access? E.g. do you see notifications about new Whatsapp messages and the like on your watch?

**Comment by JPFrancoia** [comment]
yes, it has all the permissions possible. :/

**Comment by vanous** [comment]
Weather location is set it in the weather notification app. Either fixed or by GPS.

**Comment by vanous** [comment]
Have you checked this? https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather

**Comment by vanous** [comment]
See my settings:

<img src="https://user-images.githubusercontent.com/3680926/63638585-9048fe00-c68a-11e9-840a-03d9d1366d19.jpg" width=150/> <img src="https://user-images.githubusercontent.com/3680926/63638586-90e19480-c68a-11e9-9ee4-a128b9ade0b5.jpg" width=150/> <img src="https://user-images.githubusercontent.com/3680926/63638587-90e19480-c68a-11e9-8fd1-00ff79a38564.jpg" width=150/>

**Comment by vanous** [comment]
Just tested on fresh device, no issues:
- installed weather notification app
- set location
- enabled GB skin
- opened up top notification on phone
- updated weather (refresh)
- checked on device: weather shown.

Hope this helps :)

**Comment by tomcat-xx** [comment]
My issue is: Weather information on the Mi Band is updated for current location (from weather notification app) but not location name shown on the Mi Band. It is still showing the location from sync with original Mi Fit app some weeks ago.

**Comment by vanous** [comment]
Can please clarify?

>Weather information on the Mi Band is updated for current location (from weather notification app)
> It is still showing the location from sync with original Mi Fit app some weeks ago.

This contradicts each other. 

Where exactly do you see the location name?

**Comment by tomcat-xx** [comment]
On the Mi Band weather screen below weather information (current, min, max, air index) there is location symbol and a scrolling text which shows location name. Weather Notification app is detection and showing correct location. No difference between setting fixed location or automatic detection.

**Comment by JPFrancoia** [comment]
@vanous : yes, I did exactly what you mentioned (see my first message, I read the wiki about weather). I also did all the points in your check list. My settings in weather notifications are exactly (I repeat: extacly) the same, apart of course for the location.


But as @tomcat-xx just said, the weather shown (temperature min/max, air index) is in agreement with the location set in weather notification. Except that the location name displayed under this info isn't.

E.g: My mi band 4 weather location is set to Cambridge. if I set my location in weather notifiation to paris and refresh, the weather info on the watch will be in sync with paris weather. But the city name (next to location icon, under the temperature) displayed in the weather menu is still Cambridge.

Good catch @tomcat-xx

**Comment by vanous** [comment]
Hmm, on the Bip od MB3, there is no location text, or I have never seen it as I didn't connect it with MiFit. Perhaps GB doesn't update that portion at the moment?

**Comment by JPFrancoia** [comment]
Here is an image of the situation. Don't pay attention to the location displayed at the moment, I accidentally updated it when I turned on the Mi fit app.
![20190824_180745(0)](https://user-images.githubusercontent.com/2399090/63639950-92b35400-c69a-11e9-8c5b-04e435ecdff1.jpg)

**Comment by vanous** [comment]
I see. I would suggest to rename the ticket to "Location name shown on MB4 not updated", plus update the original text to make it clear that weather information is updated but the location displayed on the band is not.

**Comment by ashimokawa** [comment]
Ok, will investigate on the issue. 

And the next release will have lineage os weather support for lineage 16.0, then you do not need weather notification if you have lineage os and prefer that. Still you would need the openweathermap weather provider from https://download.lineageos.org/extras and an api key for owm...

**Comment by tomcat-xx** [comment]
Seems this does not work for me (with Weather Notification as location provider). Shouldn't it?

**Wearable device is:**
Mi Band 4
FW: 1.0.5.55/56 (for both)

**Android version is:**
8.0.0

**Gadgetbridge version is:**
0.36.0

**Comment by ashimokawa** [comment]
@tomcat-xx 
Yes, it should work, I will re-check. Are you sure that weather actually updated in weather notification? All use the same api key and it is rate-limited

**Comment by tomcat-xx** [comment]
I can switch from automatic detection to manual setting the location, then set different locations. Weather information (current, min, max temperature) changes directly in Weather notification and on the Band. Current location in Weather notification (displayed below heading "Weather" and above current date and time also changes, but not on the Mi Band. Also automatic detected locations are not displayed when they change.

**Comment by ashimokawa** [comment]
@tomcat-xx 
Yes, you were right, fixed in master really this time.

**Comment by LinkForce** [comment]
I updated gadgetbridge today but I still have the issue with the weather location not changing even the changelog saying it should be fixed. Using MI band 4 on Android 9.

**Comment by tomcat-xx** [comment]
Version with "real fix" (see  ashimokawa's comment above) has not been released so far.

**Comment by LinkForce** [comment]
Weird, because this fix was one of the items in the changelog after updating. Gonna wait then.

**Comment by vanous** [comment]
Try now,  update 0.36.1 has landed in the F-droid.

**Comment by tomcat-xx** [comment]
Yes, works. And not only this fix ...
