### ISSUE TITLE
K9 mail notifications with old mails

### ISSUE THREAD

**Issue by IzzySoft** [Freeyourgadget/Gadgetbridge#373]
I've noticed a bunch of old mails (marked unread) pop up on the Pebble from time to time – without a corresponding notification on the Android device. Is that a known issue? Something I could fix myself?

**Comment by danielegobbetti** [comment]
It happened to me exactly once and I thought it was because I had a spotty internet connection and never thought about it again.

Could you capture a log and send it to us? I doubt we can do much as I believe it's k9 doing weird things with its notifications, but we can try. I will also try to find in my logs when this happened, but it'll hard.

Just to gather some more info, can you describe your k9 and server configuration? In my case I have:
- two IMAP accounts
- with server side filtering
- with push email on the inbox of one server, polling on some subfolders (the github notifications' one, for instance ;-)), other server is only polling
- the issue happened on the server with push 

If you can tell what's different in your configuration we can exclude some research paths. Thanks!

**Comment by IzzySoft** [comment]
Thanks, @danielegobbetti – as it happens irregularly, I can't send any logs straight away. But I'll do as soon as it happens again. What logs would you be interested in? As I can't find an entry in the Debug menu, I assume a snippet of the logcat should do?

As for the configuration: quite similar to yours.

* 3 IMAP accounts (all on the same server, which I control as well)
* server side filtering
* no pushing, all set to poll the Inbox (had to fiddle a lot to keep it at that). Reported "old mails" always come from Inboxes.
* as I have no push, here it happens on pull. Reported mails are usually several weeks old already – while poll intervals are 30min, 1h, 12h. IIRC the account with 12h polling wasn't affected, but I'm not sure.

If anything else could be relevant, let me know and I'll provide the required details.

**Comment by tecufanujacu** [comment]
I have the same identical problem with the aosp email client in cm13, when I receive a new email and I don't open it so i is unreaded I receive continuous notifications on the watch for the same already received email.
In my case I have only a gmail account configured in IMAP with push notifications and without any server side filtering.
For now I can't get a log because I have to factory reset  the phone to try to solve an abnormal battery drain but If needed I can get it in the next days.

**Comment by IzzySoft** [comment]
So it looks like it's not just K9, but "new mail notification" in general. Thanks for chiming in, @tecufanujacu !

**Comment by ashimokawa** [comment]
No, no.
These are two totally different issues.

For K9 we have special support.
For the CM13 client NOT.
If that pops up an notification again it is not our fault.

For K9 it might be our bug.

**Comment by tecufanujacu** [comment]
@ashimokawa 
So this only is a coincidence?
The email client is the only app that causes multiple notifications on the watch.

**Comment by IzzySoft** [comment]
Same here: "older stuff" reported to the Pebble as notification (but not turning up as such on the Android device) is restricted to mail (here: k9). Cannot remember a single one from a different source.

**Comment by sjp4** [comment]
You might want to look into how notification stacking is affecting this: https://developer.android.com/training/wearables/notifications/stacks.html

A lot of apps, when there are multiple non-dismissed notifications stacked up, will re-send every one of them as a new notification when a new message arrives, so some de-duping is required based on content (and record-keeping of previously received notifications). The dups will often have the same id/key - but some apps will also send new messages with a repeated key, so that can't be reliably used to de-dup them.

**Comment by IzzySoft** [comment]
@sjp4 strangely, those "old notifications" for me turn up even if there are no new ones, so that cannot be the single source. I've tried explicitly disabling "standard notifications" for K9: feels like that improves the situation, but I'm not sure yet. Just today I had a few ones I coudn't cross-check fast enough (was in a meeting), so I cannot say a thing for sure (will do as soon as I can).

**Comment by sjp4** [comment]
Any chance they turn up when you read one of the other messages e.g. on your laptop? That can also trigger all of the notifications to be regenerated on the phone, to remove the 'read' one.

**Comment by IzzySoft** [comment]
While sitting in a meeting, where I have to make a presentation? Unlikely :) There are some other clients logged in which download mail, yes, but 1) they don't mark them read without me opening them, and 2) they don't re-download mail from the week before (for me it was always old mail which was not yet marked read, but had a bunch of other mails "ahead it" that where newer, state mixed (i.e. some read, some not).

**Comment by danielegobbetti** [comment]
Can you please test disabling k9 support in GB? The notifications should come in as general notifications anyway and possibly the issue should be solved.
I have to say I didn't experience this issue when using k9 5.1x and am not now on 5.2 either, so it might have been a k9 bug.

Either way, please close the issue if you think it's solved, we can reopen it later if the problem reappears.

**Comment by IzzySoft** [comment]
Thanks for the reminder, @danielegobbetti – always wanted to cross-check it that way as well, and always forgot (btw, I still have the issue with the latest k9 recently updated from F-Droid). Besides, what's the relation then to #489 ?

I have now set "K9-Mail" to "never", let's see what that does (should switch back to "standard notifications" then for k9 I assume?). Wanted to uncheck it in the blacklist, but the checkmark was gone already? I'm sure I had it set. Strange, very strange…

**Comment by IzzySoft** [comment]
@danielegobbetti I now have switched off the k9 support for about a week. Didn't get a single old mail advertised since.

But before you call that a "solution": it is almost more annoying in certain situations. Imagine the following scenario:

* new mails are checked for once every 30 min
* within 25 min, 5 new mails have arrived

Now comes the next check. How many notifications will I receive on my watch? I'd expected 5. But I get 9: first mail, second mail, notification that there are 2 new mails, third mail, notification there are 3 new mails, 4th mail, there are 4 new mails, etc. And I only have sender and subject (while k9 support adds the first paragraph of the mail – which I believe was just added to the "standard notifications" in main).

Yuck. So my choices are Devil or Beelzebub / pest or cholera? Makes it hard to chose wisely :stuck_out_tongue_winking_eye:

What those "old mails" have in common, as far as I can tell: they're old, but still marked "unread". Hopefully this gives you a pointer…

**Comment by ashimokawa** [comment]
@IzzySoft 
Hey that's cool. If we can filter out these summary notifications "2 new mails" etc. everything should be perfect and we can remove the crappy k9 receiver, right?

**Comment by ashimokawa** [comment]
Done, I vote for removing the k9 receiver

**Comment by IzzySoft** [comment]
@ashimokawa So I understood that correctly: with #489 added and those "summary notifications" removed, it should work like the "k9 receiver" just without those "zombie notifications"? In that case, I second your vote. But I'd suggest to first have the new code tested for a little while, just to make sure. Set the k9-receiver to "deprecated" meanwhile, and have it turned off by default (on new installations) – but postpone the removal until at least one other user confirms or I don't complain for a few weeks :speak_no_evil:

**Comment by ashimokawa** [comment]
@IzzySoft 
Yes, you understood correctly ;) It seems to work like that here now

**Comment by IzzySoft** [comment]
@ashimokawa mega cool – looking forward to the next release then so I can see for myself :)

Still, let's keep the "k9 receiver" in for one more version at least (as deprecated and disabled by default on new installations), until we can definitely say it's no longer needed. Maybe have a popup on update (err, place a bold text in the Changelog which pops up anyway) that people should switch over and report if there are any issues. Currently that's just tested by you and soon by me, a wider base gives more confidence :stuck_out_tongue_winking_eye:

**Comment by IzzySoft** [comment]
OK, got the first "old mail" again with v0.17 and standard notifications. Thanks to the new format, I got curious – and it seems it's all K9's fault: The notification showed up with being from "right now" (also on the Android device), while the mail was several days old. So it looks like K9 is pushing notifications for old mails – not GB "pulling them up from nowhere". Yuck. Seems like we have to move that issue to their end.

PS: 0.17 looks great! :+1:

**Comment by IzzySoft** [comment]
PS: [Filed an issue with k9](https://github.com/k9mail/k-9/issues/2092) after checking that nobody else did. There was no such issue yet, neither open nor closed. Everyone else affected, please join in there and confirm.

**Comment by IzzySoft** [comment]
**UPDATE:** Guess I figured how to reproduce it. Can everybody else experiencing this please cross-check and then chime in to the [issue over there](https://github.com/k9mail/k-9/issues/2092#issuecomment-275948036) to give it some weight? If there's more than just one confirmation, it's more likely to get fixed – and I included a suggestion for a fix with my update there.

**Comment by danielegobbetti** [comment]
Closing this on our end.
