### ISSUE TITLE
JavaBridge error/warning on a QR Generator app.

### ISSUE THREAD

**Issue by john453** [Freeyourgadget/Gadgetbridge#421]
Using this app (**QR Generator** _by Christian Reinbacher_) with Gadgetbridge give off this error below and the QR that appear is not shown on Pebble Time Steel.

app: - https://apps.getpebble.com/en_US/application/535e84d0af59179a46000088 

`18:28:51.110 [JavaBridge] WARN  n.f.g.u.GB - Discarded key qrcode, not found in the local configuration and is not an integer key.`

The log file is attached:
[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/556605/gadgetbridge.log.txt)

**Comment by ashimokawa** [comment]
Fixed, there were actually two bugs preventing this (this one and #419)
Fix will be in the next release.

**Comment by andyb9** [comment]
the JavaBridge error/warning has indeed been fixed, :+1: 

However the app **QR Generator** still doesnt work as it should.

If you '_load saved configuration_' via '_configure_' option for the app with Gadgetbridge and '_send this data to pebble_' to the pebble, it does then shows the QR Code on the pebble as it should, **_but only once_** and also only the QR code for _personal details_ and no QR Code for the other 4 possible QR info ie _work details_. 

But most important - when you exit the app and then go back into it via app menu, it shows a blank screen and only work when you go back to Gadgetbridge and '_load saved configuration_' and sent it back to the pebble. :disappointed:

**Comment by ashimokawa** [comment]
@andyb9 
Yes, that is because QR Generator somehow does not store anything but always relies on a phone connection to fetch data again, which is stupid. Those QR codes only carry a few bytes of data, it would make sense to save them on the watch. We would have to patch QR Generator, everything else does not really make sense.

Also I am not sure if QR Generator actually generates anything, it seems to generate QR codes via internet and only send the resulting data to the watch. 

And why should anyone enter their personal details on some random watchface creator's site? Oh, because nobody cares, I forgot :grinning: 

Seriously this project should do two things:

1) Actually store data on the watch
2) Use a LOCAL javascript to generate QR codes
