### ISSUE TITLE
Pebble music control PowerAMP track data

### ISSUE THREAD

**Issue by Avamander** [Freeyourgadget/Gadgetbridge#536]
Using PowerAMP to play my music the Pebble music control app shows nothing where it should show the title, length and artist.

Pebble Time 4.3 (snowy_dvt)
Android 4.4.4 (LG D605)
GadgetBridge 0.7.12

**Comment by Avamander** [comment]
http://forum.powerampapp.com/index.php?/topic/5511-can-i-send-current-song-info-to-a-web-server/&do=findComment&comment=21114

"Poweramp sends current track info via own API and via standard Android API, so you can listen to one of those (with Broadcast Receiver) and re-send to whatever target you need (e.g. http server). Check our SDK for example app."

https://github.com/maxmpz/powerampapi/blob/master/poweramp_api_lib/src/com/maxmpz/poweramp/player/PowerampAPI.java

**Comment by danielegobbetti** [comment]
The issue is (possibly) fixed in master, as now we listen for more actions by the standard android API. I didn't test with poweramp as I don't have google play store on my devices.

**Comment by Avamander** [comment]
@danielegobbetti http://powerampapp.com/download-poweramp/

**Comment by danielegobbetti** [comment]
Installed on a spare device (API level 19) and seemed to work well except for the position updates that are not reported (i.e. song name and artist and total duration are shown, but the progress bar remains stuck at 00:00).

**Comment by Avamander** [comment]
Tested the latest master branch on my LG D605, the artist and song title are successfully displayed on my Pebble Time, nice work!

**Comment by Avamander** [comment]
https://github.com/Freeyourgadget/Gadgetbridge/pull/550

**Comment by danielegobbetti** [comment]
@Avamander since the update hit fdroid can you please confirm the issue is resolved and, if yes, close.

**Comment by Avamander** [comment]
Not resolved fully as the progress is not being updated unless an intent is received. 
a) Track progress is stuck
b) When disconnected the status is lost and not updated

**Comment by danielegobbetti** [comment]
That part is actually solved on android version >= 5 where the media notifications are part of the operating system provided features.

**Comment by Avamander** [comment]
But that still means it's not fully solved though.
